project:
  type: website

website:
  title: "Pablo Serrano - Universidad Carlos III de Madrid"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: students.qmd
        text: Students
      - href: service.qmd
        text: Service

right:
      - icon: google-scholar
        href: https://scholar.google.com/citations?user=YOUR_ID
      - icon: github
        href: https://github.com/pbluc3m
        
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true




