project:
  type: website
  output-dir: docs

website:
  title: "Pablo Serrano - Universidad Carlos III de Madrid"
  navbar:
    background: "#002b54" # UC3M Navy
    type: dark           # Makes text white
    left:
      - href: index.qmd
        text: Home
      - href: bio.qmd
        text: Bio
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Research
      - href: students.qmd
        text: Students
      - href: service.qmd
        text: Service
      - href: talks/index.qmd
        text: Talks

right:
      - icon: google-scholar
        href: https://scholar.google.com/citations?user=YOUR_ID
      - icon: github
        href: https://github.com/pbluc3m
        
format:
  html:
    css: styles.css
    toc: true



